//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingBook.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorites
    {
        public int FavoriteID { get; set; }
        public int AuthorID { get; set; }
        public int RecipeID { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Recipes Recipes { get; set; }
    }
}
