//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingBook.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeTags
    {
        public int RecipeTagID { get; set; }
        public int RecipeID { get; set; }
        public int TagID { get; set; }
    
        public virtual Recipes Recipes { get; set; }
        public virtual Tags Tags { get; set; }
    }
}
